- debug:
    msg: "El access key es: {{ aws_access_key_id }} + {{ aws_secret_access_key }}"

- name: Deleting old key
  ec2_key:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    name: "{{ key_name }}"
    state: absent

- name: Creating new key
  ec2_key:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    name: "{{ key_name }}"
    key_material: "{{ lookup('file', 'files/id_rsa.pub') }}"
    state: present