- name: Create the stack
  cloudformation:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    stack_name: "{{ myapp_stack }}"
    state: "present"
    region: "{{ aws_region }}"
    tags:
        environment: "{{ environment_tag }}"
    template: roles/aws_cloudformation/files/createstack.json
    template_parameters:
        KeyName: "{{ key_name }}"
        InstanceType: "{{ instance_type }}"
        SSHLocation: "0.0.0.0/0"
        WebServerSecurityGroup: "MiEC2SG"
        DBName: "{{ DBName }}"
        DBUsername: "{{ DBUsername }}"
        DBPassword: "{{ DBPassword }}"

    on_create_failure: DELETE
  register: stack

- set_fact:
    db_endpoint: "{{stack.stack_outputs.Database}}"