packages:
    - nginx
    - php73
    - php73-php-pgsql
    - php73-php-soap
    - php73-php-xml
    - php73-php-devel
    - php73-php-gd 
    - php73-php-mbstring
    - php73-php-fpm
    - php73-php-curl
    - php73-php-pear
    - php73-php-pecl-mcrypt
    - php73-php-pecl-zip
    - php73-php-bcmath
    - php73-php-pdo
    - php73-php-cli

utils:
    - tmux
    - vim
    - net-tools
    - yum-utils
    - bzip2
    - unzip
    - git